name: Docker Build and Push

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push
        run: |
          docker buildx build -f build.Dockerfile --platform linux/arm64 . --tag ghcr.io/milgradesec/cloudflared:2021.6.0 --tag ghcr.io/milgradesec/cloudflared:latest --push
